# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion del Servicio')),
                ('precio', models.IntegerField(null=True)),
                ('contrato', models.BooleanField(default=False, help_text='Marque si el el servicio lleva contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
