# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_servicios_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='duracion',
            field=models.CharField(blank=True, choices=[('1 MES', '1 MES'), ('3 MESES', '3 MESES'), ('6 MESES', '6 MESES'), ('1 ANO', '1 ANO')], max_length=20, null=True, verbose_name='Tiempo del contrato'),
        ),
    ]
