# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20170910_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duracionservicios',
            old_name='meses',
            new_name='nombre',
        ),
    ]
