# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20170910_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio del Servicio'),
        ),
    ]
