# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20170910_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duracionservicios',
            name='nombre',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='Cantidad de Tiempo'),
        ),
    ]
