# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_auto_20170910_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duracionservicios',
            name='nombre',
            field=models.CharField(max_length=20, null=True, verbose_name='Cantidad de Tiempo'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='duracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.DuracionServicios', verbose_name='Duraciones posibles del servicio'),
        ),
    ]
