# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_auto_20170920_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='duracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.DuracionServicios', verbose_name='Duraciones posibles del servicio'),
        ),
    ]
