# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_auto_20170920_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duracionservicios',
            name='nombre',
            field=models.IntegerField(null=True, verbose_name='Cantidad de Tiempo'),
        ),
    ]
