# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_auto_20170920_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio del Servicio'),
        ),
    ]
