# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_auto_20171104_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duracionservicios',
            name='nombre',
            field=models.CharField(default=1, max_length=20, verbose_name='Cantidad de Tiempo'),
            preserve_default=False,
        ),
    ]
