# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20170920_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Datos de la Facturacion'},
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fac_client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='dir_fac',
            new_name='fac_dir',
        ),
    ]
