# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20170920_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Dato', 'verbose_name_plural': 'Datos de Facturacion'},
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fac_dir',
            new_name='dir_fac',
        ),
    ]
