# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_auto_20170920_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fac_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la Factura'),
        ),
    ]
