# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_auto_20170920_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fac_client',
            new_name='fac_cliente',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='num_fact',
            new_name='num_fac',
        ),
    ]
