# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0014_auto_20170921_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factura',
            new_name='Facturas',
        ),
    ]
