# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0015_auto_20170921_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='IVA de la Factura'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Total de la Factura'),
        ),
    ]
