# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contacto', models.DateTimeField(null=True)),
                ('actividad_registrada', models.CharField(max_length=255)),
                ('volver_contactar', models.BooleanField(default=False, help_text='Marcar en caso de volver a contactar a futuro', verbose_name='Volver a Contactar')),
                ('fecha_prox_contacto', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Actividad de Cliente',
                'verbose_name_plural': 'Actividades de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Potenciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombres Completos', max_length=255, verbose_name='Nombres')),
                ('apellido', models.CharField(help_text='Apellidos Completos', max_length=255, verbose_name='Apellidos')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Telefono Celular')),
                ('telefono_h', models.IntegerField(blank=True, help_text='Opcional si posee', null=True, verbose_name='Telefono de Habitacion')),
                ('personas', models.BooleanField(default=False, help_text='Marque en caso de poseer', verbose_name='Posee personas a su cargo')),
                ('cantidad_p', models.IntegerField(default=0, null=True, verbose_name='Cantidad de personas a su cargo')),
                ('adultos', models.BooleanField(default=False, help_text='Marque en caso de poseer', verbose_name='Adulto Mayor a su cargo')),
                ('valencia', models.BooleanField(default=False, help_text='Marque de ser correcto', verbose_name='Reside en Valencia')),
                ('medio_contactado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalidades.MedioContacto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tu usuario')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalidades.ZonasValencia', verbose_name='Seleccione la zona donde reside')),
            ],
            options={
                'verbose_name': 'Cliente Potencial',
                'verbose_name_plural': 'Clientes Potenciales',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='cliente_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Potenciales', verbose_name='Cleinte Potencial'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='medio_contactado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalidades.MediosActividad'),
        ),
    ]
