# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170622_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='medio_contactado',
        ),
        migrations.RemoveField(
            model_name='potenciales',
            name='medio_contactado',
        ),
        migrations.RemoveField(
            model_name='potenciales',
            name='valencia',
        ),
        migrations.RemoveField(
            model_name='potenciales',
            name='zona',
        ),
        migrations.AlterField(
            model_name='potenciales',
            name='adultos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], help_text='Marque en caso de poseer', max_length=3, verbose_name='Adulto Mayor a su cargo'),
        ),
        migrations.AlterField(
            model_name='potenciales',
            name='personas',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], help_text='Marque en caso de poseer', max_length=2, verbose_name='Posee personas a su cargo'),
        ),
    ]
