# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20170627_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potenciales',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tu usuario'),
        ),
    ]
