# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20170923_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potenciales',
            old_name='usuario',
            new_name='user',
        ),
    ]
