# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediosactividad',
            options={'verbose_name': 'Medio de Contacto para Actividad', 'verbose_name_plural': 'Medios de Contacto para Actividades'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
