# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='enfermedad_circulatorio',
            field=models.CharField(blank=True, choices=[('Trastorno en la presion arterial', 'Trastorno en la presion arterial '), ('Alteraciones cardiacas', 'Alteraciones cardiacas'), ('Angina de pecho', 'Angina de pecho '), ('Infarto de miocardio', 'Infarto de miocardio'), ('Otras enfermedades relacionados', 'Otras enfermedades relacionados:'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Circulatorias'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='enfermedad_digestivo',
            field=models.CharField(blank=True, choices=[('Enfermedades del higado', 'Enfermedades del higado'), ('Ulcera gastroduodenal', 'Ulcera gastroduodenal'), ('Dispepcia', 'Dispepcia'), ('Gastritis', 'Gastritis'), ('Otras enfermedades', 'Otras enfermedades'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Digestivas'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='enfermedad_respiratoria',
            field=models.CharField(blank=True, choices=[('Bronquitis', 'Bronquitis Cronica'), ('Tuberculosis', 'Tuberculosis'), ('Asma', 'Asma'), ('Otras', 'Otras'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Respiratorias'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='estatura',
            field=models.CharField(blank=True, max_length=7, verbose_name='Indique su Estatura'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='otras_enfermedades',
            field=models.CharField(blank=True, choices=[('Reumatismo', 'Reumatismo'), ('Artritis', 'Artritis'), ('Hemorragias de cualquier indole', 'Hemorragias de cualquier indole'), ('Perdida del conocimiento', 'Perdida del conocimiento'), ('Enfermedades en los huesos', 'Enfermedades en los huesos'), ('Convulsiones', 'Convulsiones'), ('Paralisis', 'Paralisis'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Otras Enfermedades'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='peso',
            field=models.CharField(blank=True, max_length=7, verbose_name='Indique su peso'),
        ),
    ]
