# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_remove_contratado_domicilio_laboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratado',
            name='indique_circulatorio',
        ),
        migrations.RemoveField(
            model_name='contratado',
            name='indique_digestivo',
        ),
        migrations.RemoveField(
            model_name='contratado',
            name='indique_otras',
        ),
        migrations.RemoveField(
            model_name='contratado',
            name='indique_respiratoria',
        ),
    ]
