# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_auto_20170628_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='enfermedades_importantes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Otras Importantes'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='nombre_sector',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Sector'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='nombre_ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Ubicacion'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='piso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='rif',
            field=models.CharField(blank=True, help_text='Opcional si posee', max_length=20, verbose_name='R.I.F.'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Servicios', verbose_name='Servicio a Contratar'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='telefono_o',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono Oficina'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalidades.Ubicacion', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalidades.Vivienda', verbose_name='Vivienda'),
        ),
    ]
