# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_auto_20170628_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiario_enfermedad_circulatorio',
            field=models.CharField(blank=True, choices=[('Trastorno en la presion arterial', 'Trastorno en la presion arterial '), ('Alteraciones cardiacas', 'Alteraciones cardiacas'), ('Angina de pecho', 'Angina de pecho '), ('Infarto de miocardio', 'Infarto de miocardio'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Circulatorias'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiario_enfermedad_digestivo',
            field=models.CharField(blank=True, choices=[('Enfermedades del higado', 'Enfermedades del higado'), ('Ulcera gastroduodenal', 'Ulcera gastroduodenal'), ('Dispepcia', 'Dispepcia'), ('Gastritis', 'Gastritis'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Digestivas'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiario_enfermedad_respiratoria',
            field=models.CharField(blank=True, choices=[('Bronquitis', 'Bronquitis Cronica'), ('Tuberculosis', 'Tuberculosis'), ('Asma', 'Asma'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Respiratorias'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='enfermedad_circulatorio',
            field=models.CharField(blank=True, choices=[('Trastorno en la presion arterial', 'Trastorno en la presion arterial '), ('Alteraciones cardiacas', 'Alteraciones cardiacas'), ('Angina de pecho', 'Angina de pecho '), ('Infarto de miocardio', 'Infarto de miocardio'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Circulatorias'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='enfermedad_digestivo',
            field=models.CharField(blank=True, choices=[('Enfermedades del higado', 'Enfermedades del higado'), ('Ulcera gastroduodenal', 'Ulcera gastroduodenal'), ('Dispepcia', 'Dispepcia'), ('Gastritis', 'Gastritis'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Digestivas'),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='enfermedad_respiratoria',
            field=models.CharField(blank=True, choices=[('Bronquitis', 'Bronquitis Cronica'), ('Tuberculosis', 'Tuberculosis'), ('Asma', 'Asma'), ('Ninguna', 'Ninguna')], help_text='Indique si Padece', max_length=50, verbose_name='Enfermedades Respiratorias'),
        ),
    ]
