# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_auto_20170630_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='fecha_n',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
