# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_auto_20170908_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratado',
            options={},
        ),
    ]
