# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_auto_20170909_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratado',
            name='modalidad_cuotas',
            field=models.CharField(choices=[('Contado', '1'), ('Bianual', '2'), ('Trimestral', '4'), ('Mensual', '12')], max_length=10, null=True, verbose_name='Escoja la cantidad de cuotas en las que realizara sus pagos'),
        ),
    ]
