# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_auto_20170920_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Servicios', verbose_name='Servicio a Contratar'),
        ),
    ]
