# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 09:44
from __future__ import unicode_literals

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_auto_20170920_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratado',
            name='id',
        ),
        migrations.AlterField(
            model_name='contratado',
            name='numcontrato',
            field=models.CharField(default=contratos.models.incremental, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
