# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 09:47
from __future__ import unicode_literals

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_auto_20170920_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratado',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratado',
            name='numcontrato',
            field=models.CharField(default=contratos.models.incremental, editable=False, max_length=20),
        ),
    ]
