# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20170920_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratado',
            name='fecha_contratacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Contratacion'),
        ),
        migrations.AddField(
            model_name='contratado',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiracion'),
        ),
    ]
