# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_auto_20170921_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratado',
            name='precio_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio Total del Contrato'),
        ),
    ]
