# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_contratado_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='piso',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
