# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_auto_20171007_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratado',
            name='estatus',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
