# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_contratado_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='estatus',
            field=models.BooleanField(verbose_name='Estatus'),
        ),
    ]
