# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_auto_20171107_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='fecha_expiracion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
